### ISSUE TITLE
.npy - feature extract file

### ISSUE THREAD

**Issue by DungVo1507** [GowthamGottimukkala/I3D_Feature_Extraction_resnet#2]
Thank you so much for creating this useful repo!

After I follow the instructions in the Usage section but the output I get in /temp/ is the frames of the video.
Please tell me how to get a .npy file and shape (10, n/16, 2048) like in this paper [Weakly-supervised Video Anomaly Detection with Robust Temporal Feature Magnitude Learning](https://arxiv.org/pdf/2101.10030.pdf).

Looking forward to your help

**Comment by 252965307** [comment]
同问

**Comment by GowthamGottimukkala** [comment]
> Thank you so much for creating this useful repo!
> 
> After I follow the instructions in the Usage section but the output I get in /temp/ is the frames of the video.
> Please tell me how to get a .npy file and shape (10, n/16, 2048) like in this paper [Weakly-supervised Video Anomaly Detection with Robust Temporal Feature Magnitude Learning](https://arxiv.org/pdf/2101.10030.pdf).
> 
> Looking forward to your help

The frames in the temp folder is not the output, the .npy file is generated along with the temp folder with 1 * n/16 * 2048 dimension. 
You can see it here
https://github.com/GowthamGottimukkala/I3D_Feature_Extraction_resnet/blob/340bbec171bd084c71736df61b4aa137b6eb5bf8/main.py#L36

**Comment by DungVo1507** [comment]
Thank you so much for helping me,
Below is the output after I run the command line: `!python main.py --datasetpath=samplevideos/ --outputpath=output`:
```
Received Pretrained model..
Generating for samplevideos/Abuse001_x264.mp4
Preprocessing done..
batchsize 32
^C
```
It doesn't print "Obtained features of size:" and "done in {0}." This means I still haven't created the .npy.
Can you explain what problem I'm having?
Thank you!

**Comment by GowthamGottimukkala** [comment]
It seems that it is exiting inside the run function of extract_features.py. I would suggest you to keep debug points(or print statements) in extract_features.py and check where it is exiting

**Comment by DungVo1507** [comment]
Thank you, that error was due to my RAM not being enough but I got through.
I am getting this error even though I installed ffmpeg using the command line: `pip3 install ffmpeg-python`
```
Received Pretrained model..
Generating for samplevideos/Nor_006.mp4
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    generate(args.datasetpath, str(args.outputpath), args.pretrainedpath, args.frequency, args.batch_size, args.sample_mode)
  File "main.py", line 33, in generate
    ffmpeg.input(video).output('{}%d.jpg'.format(temppath),start_number=0).global_args('-loglevel', 'quiet').run()
  File "/home/object_detection/.local/lib/python3.8/site-packages/ffmpeg/_run.py", line 313, in run
    process = run_async(
  File "/home/object_detection/.local/lib/python3.8/site-packages/ffmpeg/_run.py", line 284, in run_async
    return subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

```
I don't know where did I go wrong?

**Comment by Nandini2801** [comment]
After running !python main.py --datasetpath=samplevideos/ --outputpath=output
The code is exiting after showing 
Received Pretrained model..
Can you help me with this regard?

**Comment by dhruva-12** [comment]
After executing command python main.py --datasetpath=samplevideos/ --outputpath=output
The code is exiting after showing
Received Pretrained model..
Can you help me with this regard?
